In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px

In [6]:
df = pd.read_csv("kenya_psa_dataset_translations.csv")
df.head()

,PSA_ID,Domain,English,Kiswahili2,Somali,Dholuo,Kiswahili,Target_Languages,Source,Date,Metadata,Date_dt,en_len,sw_len
0,PSA000001,health,The Ministry of Health advises all residents t...,Wizara ya Afya inawashauri wakazi wote kuchems...,Wasaaradda Caafimaadka waxay kula talinaysaa d...,NaN,Wizara ya Afya inashauri wakazi wote kuchemsha...,"{""Somali"": ""placeholder"", ""Kikuyu"": ""placehold...",IEBC Kenya,2024-11-23,"{""type"": ""handcrafted_template"", ""psa_score"": ...",2024-11-23,115,115
1,PSA000002,health,URGENT: Avoid unnecessary travel to Ebola-affe...,HARAKA: Epuka kusafiri bila lazima kwenda maen...,DEGDEG AH: Ka fogow safar aan loo baahnayn oo ...,NaN,HARAKA: Epuka usafiri usio wa lazima kwenye ma...,"{""Somali"": ""placeholder"", ""Kikuyu"": ""placehold...",Ministry of Health,2024-01-18,"{""type"": ""handcrafted_template"", ""psa_score"": ...",2024-01-18,130,152
2,PSA000003,health,Parents are reminded to ensure children under ...,Wazazi wanakumbushwa kuhakikisha watoto walio ...,Waalidiinta waxaa la xasuusinayaa inay hubiyaa...,NaN,Wazazi wamekumbushwa kuhakikisha watoto chini ...,"{""Somali"": ""placeholder"", ""Kikuyu"": ""placehold...",Ministry of Health,2025-07-17,"{""type"": ""handcrafted_template"", ""psa_score"": ...",2025-07-17,108,120
3,PSA000004,health,The Social Health Authority warns the public a...,Mamlaka ya Afya ya Jamii inaonya umma dhidi ya...,Hay'adda Caafimaadka Bulshada waxay uga digays...,NaN,Mamlaka ya Afya ya Jamii inawaonya umma dhidi ...,"{""Somali"": ""placeholder"", ""Kikuyu"": ""placehold...",Ministry of Education,2024-10-20,"{""type"": ""handcrafted_template"", ""psa_score"": ...",2024-10-20,158,155
4,PSA000005,health,All travelers from yellow fever endemic countr...,Wasafiri wote kutoka nchi zilizoathiriwa na ho...,Dhammaan dadka safarka ah ee ka imanaya wadama...,NaN,Wasafiri wote kutoka nchi zinazoathiriwa na ho...,"{""Somali"": ""placeholder"", ""Kikuyu"": ""placehold...",Social Health Authority,2024-01-22,"{""type"": ""handcrafted_template"", ""psa_score"": ...",2024-01-22,111,127

In [7]:
df.isnull().sum()

PSA_ID                 0
Domain                 0
English                0
Kiswahili2             0
Somali                 0
Dholuo              5200
Kiswahili              0
Target_Languages       0
Source                 0
Date                   0
Metadata               0
Date_dt                0
en_len                 0
sw_len                 0
dtype: int64

In [9]:
#drop the kiswahili column
df = df.drop(columns=['Kiswahili'])

In [10]:
df.head()

,PSA_ID,Domain,English,Kiswahili2,Somali,Dholuo,Target_Languages,Source,Date,Metadata,Date_dt,en_len,sw_len
0,PSA000001,health,The Ministry of Health advises all residents t...,Wizara ya Afya inawashauri wakazi wote kuchems...,Wasaaradda Caafimaadka waxay kula talinaysaa d...,NaN,"{""Somali"": ""placeholder"", ""Kikuyu"": ""placehold...",IEBC Kenya,2024-11-23,"{""type"": ""handcrafted_template"", ""psa_score"": ...",2024-11-23,115,115
1,PSA000002,health,URGENT: Avoid unnecessary travel to Ebola-affe...,HARAKA: Epuka kusafiri bila lazima kwenda maen...,DEGDEG AH: Ka fogow safar aan loo baahnayn oo ...,NaN,"{""Somali"": ""placeholder"", ""Kikuyu"": ""placehold...",Ministry of Health,2024-01-18,"{""type"": ""handcrafted_template"", ""psa_score"": ...",2024-01-18,130,152
2,PSA000003,health,Parents are reminded to ensure children under ...,Wazazi wanakumbushwa kuhakikisha watoto walio ...,Waalidiinta waxaa la xasuusinayaa inay hubiyaa...,NaN,"{""Somali"": ""placeholder"", ""Kikuyu"": ""placehold...",Ministry of Health,2025-07-17,"{""type"": ""handcrafted_template"", ""psa_score"": ...",2025-07-17,108,120
3,PSA000004,health,The Social Health Authority warns the public a...,Mamlaka ya Afya ya Jamii inaonya umma dhidi ya...,Hay'adda Caafimaadka Bulshada waxay uga digays...,NaN,"{""Somali"": ""placeholder"", ""Kikuyu"": ""placehold...",Ministry of Education,2024-10-20,"{""type"": ""handcrafted_template"", ""psa_score"": ...",2024-10-20,158,155
4,PSA000005,health,All travelers from yellow fever endemic countr...,Wasafiri wote kutoka nchi zilizoathiriwa na ho...,Dhammaan dadka safarka ah ee ka imanaya wadama...,NaN,"{""Somali"": ""placeholder"", ""Kikuyu"": ""placehold...",Social Health Authority,2024-01-22,"{""type"": ""handcrafted_template"", ""psa_score"": ...",2024-01-22,111,127

In [20]:
print("Number of PSAs before dropping duplicates")
df.shape

Number of PSAs before dropping duplicates

(5200, 13)

In [19]:
#drop duplicates based on the enlgish column
df2=df.drop_duplicates(subset=['English'])
print("Number of PSAs after dropping duplicates")
df2.shape

Number of PSAs after dropping duplicates

(5011, 13)

In [18]:
# distribution of the English column by domain, create an interactive pie chart for this
domain_counts = df2['Domain'].value_counts().reset_index()
domain_counts.columns = ['Domain', 'Count']
import plotly.express as px
fig = px.pie(domain_counts, names='Domain', values='Count', title='Distribution of English PSAs by Domain', hole=0.4)

fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

In [23]:
# provide our top sources of PSAs per domain, create separate interactive bar charts for each domain
domain_groups = df2.groupby(['Domain', 'Source']).size().reset_index(name='Count')
for domain, group in domain_groups.groupby('Domain'):
    fig = px.bar(group.sort_values('Count', ascending=False),
                 x='Source',
                 y='Count',
                 color='Source',
                 color_discrete_sequence=px.colors.qualitative.Bold,
                 title=f'Top PSA Sources for {domain}',
                 labels={'Source': 'Source', 'Count': 'Number of PSAs'})
    fig.update_layout(xaxis_tickangle=-45,
                      margin=dict(l=40, r=40, t=80, b=140),
                      showlegend=False)
    fig.show()

In [24]:
domain_groups

         Domain                                 Source  Count
0   agriculture                      County Government     63
1   agriculture                             IEBC Kenya     74
2   agriculture        Kenya Meteorological Department     72
3   agriculture                        Kenya Red Cross     55
4   agriculture                Kenya Revenue Authority     67
..          ...                                    ...    ...
73     security    National Disaster Operations Centre     57
74     security  National Drought Management Authority     62
75     security                National Police Service     66
76     security                Social Health Authority     59
77     security            Teachers Service Commission     51

[78 rows x 3 columns]

In [ ]:
# source distribution: interactive chart for source_counts
source_counts = df2['Source'].value_counts().reset_index()
source_counts.columns = ['Source', 'Count']
fig = px.bar(source_counts.sort_values('Count', ascending=False),
             x='Source',
             y='Count',
             color='Source',
             color_discrete_sequence=px.colors.qualitative.Vivid,
             title='Source Counts for English PSAs',
             labels={'Source': 'Source', 'Count': 'Number of PSAs'})
fig.update_layout(xaxis_tickangle=-45,
                  margin=dict(l=40, r=40, t=80, b=140),
                  showlegend=False)
fig.show()